"""
This comment block was generated by ChatGPT

Decoder-only Transformer with genre conditioning.

--- Architecture overview ---
Input  : (B, T) token IDs  +  (B,) genre IDs
Output : (B, T, V) logits over the vocabulary for the *next* token at each position

The model is a "decoder-only" Transformer — the same architecture used by GPT.
It reads a sequence of tokens left-to-right and, at every position, predicts
what token comes next. A causal mask ensures position i can only attend to
positions 0..i (no peeking at future tokens).

--- Genre conditioning ---
A learnable genre embedding (one vector per genre) is added to every token
position before the Transformer layers. This biases the entire computation
toward the chosen genre — the model learns that the same pitch sequence
should sound different depending on whether the genre is Jazz vs Metal.

--- Tied embeddings ---
The output projection (head) shares its weight matrix with the token embedding.
This ties input and output representations and reduces parameter count with no
loss in quality — a well-established trick from language modeling research.
"""
import torch
import torch.nn as nn
from Transformer_Music.genres import N_GENRES
from Transformer_Music.tokenizer import VOCAB_SIZE, PAD

# ---------------------------------------------------------------------------
# Hyper-parameters
# ---------------------------------------------------------------------------
D_MODEL         = 256   # Size of every embedding / hidden vector.
                        # All attention heads and feed-forward layers work in this space.

N_HEADS         = 8     # Number of attention heads. Each head attends to D_MODEL/N_HEADS = 32 dims.
                        # Multiple heads let the model simultaneously focus on different
                        # aspects of the sequence (rhythm, harmony, instrument, etc.).

N_LAYERS        = 8     # Number of stacked Transformer blocks.
                        # More layers = more representational power (but slower training).
                        # 8 layers uses ~4.2 GB of GPU memory on this dataset.

DIM_FEEDFORWARD = 1024  # Width of the feed-forward sub-layer inside each Transformer block.
                        # Standard practice is 4× D_MODEL (256 × 4 = 1024).

DROPOUT         = 0.1   # Fraction of neurons randomly zeroed during training.
                        # Acts as regularization to prevent overfitting.

MAX_SEQ_LEN     = 1024  # Maximum sequence length the model can process.
                        # Must match SEQ_LEN in midi_pipeline.py.

GENRE_EMBED_DIM = D_MODEL  # Genre embedding is the same size as token embeddings
                            # so they can be added together directly.


class GenreTransformer(nn.Module):
    """
    A decoder-only Transformer that generates music conditioned on a genre label.

    Forward pass summary:
        1. Look up a D_MODEL-dim vector for each token (token embedding)
        2. Add a D_MODEL-dim positional vector for each sequence position
        3. Add the genre embedding (same vector broadcast to all positions)
        4. Drop out some values for regularization
        5. Pass through N_LAYERS causal self-attention blocks
        6. Apply final layer norm
        7. Project to vocabulary size → logits for next-token prediction
    """

    def __init__(
        self,
        vocab_size   = VOCAB_SIZE,
        d_model      = D_MODEL,
        n_heads      = N_HEADS,
        n_layers     = N_LAYERS,
        dim_ff       = DIM_FEEDFORWARD,
        dropout      = DROPOUT,
        max_seq_len  = MAX_SEQ_LEN,
        n_genres     = N_GENRES,
    ):
        super().__init__()
        self.d_model = d_model
        self.max_seq_len = max_seq_len

        # --- Embedding layers ---
        # Token embedding: maps each integer token ID to a learnable D_MODEL-dim vector.
        # padding_idx=PAD means the PAD token always maps to the zero vector and
        # its embedding is not updated during training.
        self.token_embed = nn.Embedding(vocab_size, d_model, padding_idx=PAD)

        # Positional embedding: tells the model where in the sequence each token sits.
        # Without this, the Transformer has no sense of order (attention is permutation-invariant).
        self.pos_embed = nn.Embedding(max_seq_len, d_model)

        # Genre embedding: one vector per genre. This single vector is broadcast-added
        # to every position, steering the model's predictions toward that genre's style.
        self.genre_embed = nn.Embedding(n_genres, d_model)

        self.embed_drop = nn.Dropout(dropout)

        # --- Transformer backbone ---
        # nn.TransformerEncoderLayer is a single block containing:
        #   - Multi-head self-attention (with causal mask applied in forward())
        #   - Feed-forward network (Linear → GELU → Linear)
        #   - Layer normalization and residual connections
        # norm_first=True uses "Pre-LN" ordering (LayerNorm before attention),
        # which trains more stably than the original "Post-LN" design.
        layer = nn.TransformerEncoderLayer(
            d_model = d_model,
            nhead = n_heads,
            dim_feedforward = dim_ff,
            dropout = dropout,
            activation = "gelu",    # smoother than ReLU; standard in modern LMs
            batch_first = True,     # input shape is (batch, seq, dim) — more intuitive
            norm_first = True,      # Pre-LN: more stable gradients
        )
        # Stack N_LAYERS of the above block
        self.transformer = nn.TransformerEncoder(layer, num_layers=n_layers)

        self.ln_f = nn.LayerNorm(d_model)   # final layer norm before the output head
        self.head = nn.Linear(d_model, vocab_size, bias=False)  # projects hidden → logits

        # --- Tied weights ---
        # Share the weight matrix between the input token embedding and the output head.
        # Intuition: if two tokens are similar in the input space, they should also be
        # similar predictions in the output space. Cuts parameters with no quality loss.
        self.head.weight = self.token_embed.weight

        # Initialize all weights with small Gaussian noise (standard GPT-style init)
        self.apply(self.init_weights)

    @staticmethod
    def init_weights(m):
        """Initialize linear and embedding layers with small normal weights."""
        if isinstance(m, nn.Linear):
            nn.init.normal_(m.weight, mean=0.0, std=0.02)
            if m.bias is not None:
                nn.init.zeros_(m.bias)
        elif isinstance(m, nn.Embedding):
            nn.init.normal_(m.weight, mean=0.0, std=0.02)

    def causal_mask(self, T, device):
        """
        Build a T×T upper-triangular boolean mask.

        mask[i, j] = True means position i is NOT allowed to attend to position j.
        Setting the upper triangle (j > i) to True prevents any position from
        looking at tokens that come after it — enforcing the autoregressive property.
        """
        return torch.triu(torch.ones(T, T, device=device, dtype=torch.bool), diagonal=1)

    def forward(self, tokens, genre):
        """
        tokens : (B, T) — integer token IDs, one sequence per batch element
        genre  : (B,)   — integer genre IDs, one per batch element
        returns: (B, T, vocab_size) — next-token logits for every position
        """
        B, T = tokens.shape
        assert T <= self.max_seq_len, f"seq len {T} > max {self.max_seq_len}"

        # --- 1. Build positional indices [0, 1, ..., T-1] for each batch item ---
        positions = torch.arange(T, device=tokens.device).unsqueeze(0).expand(B, T)

        # --- 2. Combine token + position + genre embeddings ---
        x = self.token_embed(tokens) + self.pos_embed(positions)
        # genre_embed(genre) is shape (B, D_MODEL); unsqueeze adds the seq dimension
        # so it broadcasts and adds the same genre vector to every token position.
        x = x + self.genre_embed(genre).unsqueeze(1)
        x = self.embed_drop(x)

        # --- 3. Causal self-attention mask ---
        # Passed to the Transformer so each position only attends to past positions.
        mask = self.causal_mask(T, tokens.device)

        # --- 4. Key-padding mask ---
        # Tells the Transformer to ignore PAD tokens (they carry no musical information).
        key_padding_mask = (tokens == PAD)

        # --- 5. Run through all N_LAYERS Transformer blocks ---
        x = self.transformer(x, mask=mask, src_key_padding_mask=key_padding_mask)

        # --- 6. Final layer norm + linear projection to vocabulary logits ---
        x = self.ln_f(x)
        logits = self.head(x)  # (B, T, vocab_size)
        return logits
