"""
This comment block was generated by ChatGPT

Training loop for GenreTransformer.

--- What this script does ---
1. Loads all pre-tokenized .npy sequences into RAM (fast tensor indexing during training)
2. Splits into train / validation sets
3. Trains the model with teacher forcing (next-token prediction)
4. Saves checkpoints so training can be resumed if interrupted

--- Teacher forcing ---
At training time we feed the model the correct token history and ask it to
predict the next token at every position simultaneously. This is more efficient
than generating one token at a time and lets us compute the loss over all T
positions in a single forward pass.

Input fed to model:   [START, t0, t1, t2, ..., t_{n-2}]
Target we compare to: [t0,    t1, t2, t3, ..., t_{n-1}]
The model learns: "given everything up to position i, what comes at position i+1?"

--- Gradient accumulation ---
With GRAD_ACCUM=2, we accumulate gradients over 2 mini-batches before updating
weights. This simulates an effective batch size of BATCH_SIZE × GRAD_ACCUM = 32
without needing extra GPU memory. Larger effective batches produce more stable
gradient estimates and often converge faster.

--- Mixed precision (AMP) ---
On CUDA, torch.amp.autocast runs the forward pass in fp16 (half precision).
fp16 arithmetic is 2× faster on modern GPUs and uses half the memory.
GradScaler compensates for fp16's smaller numeric range during backprop.
"""
import os
import csv
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
from tqdm import tqdm

from Transformer_Music.model import GenreTransformer
from Transformer_Music.tokenizer import PAD, START
from Transformer_Music.genres import GENRE_TO_IDX


DATA_ROOT = r"C:\CS-421\Final_Project\midi_data"
CKPT_DIR = r"C:\CS-421\Final_Project\checkpoints"
BATCH_SIZE = 16        # Sequences per GPU step
EPOCHS = 50            # Total training epochs
LR = 3e-4              # Peak learning rate for AdamW
WEIGHT_DECAY = 0.01    # L2 regularization coefficient
WARMUP_STEPS = 1000    # Number of steps to linearly ramp up the learning rate
VAL_SPLIT = 0.05       # Fraction of data held out for validation (5%)
GRAD_ACCUM = 2         # Accumulate gradients over this many steps before updating

os.makedirs(CKPT_DIR, exist_ok=True)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Training on: {device}\n")


class MidiDataset(Dataset):
    """
    This comment block was generated by ChatGPT

    Pre-loads the entire dataset into RAM as two large tensors.

    Why load into RAM?
      The alternative is reading .npy files from disk inside __getitem__.
      With multiple DataLoader workers, this caused random crashes (file handle
      conflicts in multiprocessing). Loading everything up front eliminates all
      disk I/O during training — __getitem__ becomes a pure tensor slice,
      which is extremely fast and requires num_workers=0 (no multiprocessing).

    Dataset layout after __init__:
      self.inputs  : (N, T) int64 — [START, t0, ..., t_{T-2}]  (model input)
      self.targets : (N, T) int64 — [t0, t1, ..., t_{T-1}]     (what model predicts)
      self.labels  : (N,)   int64 — genre index for each sequence
    """

    def __init__(self, meta_path):
        root = os.path.dirname(meta_path)
        rows = []
        # Read the metadata CSV; filter out any genres not in our current genre list
        with open(meta_path, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                if row["genre"] in GENRE_TO_IDX:
                    rows.append(row)

        print(f"Loading {len(rows)} sequences into RAM...")

        # Probe the first file to learn the sequence length (should be SEQ_LEN=1024)
        first = np.load(os.path.join(root, rows[0]["file"]))
        seq_len = first.shape[0]

        # Allocate large arrays upfront (faster than appending one by one)
        seqs = np.empty((len(rows), seq_len), dtype=np.int64)
        labels = np.empty(len(rows), dtype=np.int64)

        for i, row in enumerate(rows):
            # Load each .npy (int16 on disk) and upcast to int64 for PyTorch
            seqs[i] = np.load(os.path.join(root, row["file"])).astype(np.int64)
            labels[i] = GENRE_TO_IDX[row["genre"]]

        # --- Build teacher-forced input / target pairs ---
        # Input  = [START token] + [all tokens except the last]
        # Target = [all tokens]  (shifted one step to the right relative to input)
        # This means at position i the model sees tokens 0..i and predicts token i+1.
        starts = np.full((len(rows), 1), START, dtype=np.int64)
        self.inputs = torch.from_numpy(np.concatenate([starts, seqs[:, :-1]], axis=1))
        self.targets = torch.from_numpy(seqs)
        self.labels = torch.from_numpy(labels)

        mb = (self.inputs.numel() + self.targets.numel()) * 8 / 1e6
        print(f"  -> {mb:.0f} MB resident in RAM")

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        # Returns a single (input sequence, target sequence, genre label) triple.
        # Because everything is already in RAM as tensors, this is just a slice — very fast.
        return self.inputs[idx], self.targets[idx], self.labels[idx]


def lr_lambda(step):
    """
    Learning rate schedule: linear warmup for the first WARMUP_STEPS steps,
    then constant at the peak learning rate.

    Why warm up?
      At the start of training, the model weights are random. Large gradient
      updates from a full learning rate can destabilize training. Starting
      with a small LR and gradually increasing it avoids this.
    """
    if step < WARMUP_STEPS:
        return step / max(1, WARMUP_STEPS)  # ramp from 0 → 1
    return 1.0  # stay at peak LR for the rest of training


def main():
    # --- Build dataset and split ---
    dataset = MidiDataset(os.path.join(DATA_ROOT, "metadata.csv"))
    val_size = max(1, int(len(dataset) * VAL_SPLIT))
    train_size = len(dataset) - val_size

    # random_split with a fixed seed makes the val set reproducible across runs
    train_ds, val_ds = random_split(
        dataset, [train_size, val_size],
        generator=torch.Generator().manual_seed(42),
    )

    # num_workers=0: no multiprocessing — safe because the dataset is already in RAM.
    # pin_memory=True: speeds up CPU→GPU transfers by using pinned (page-locked) memory.
    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=True)
    print(f"Train: {train_size} | Val: {val_size}\n")

    # --- Model, optimizer, scheduler, loss ---
    model = GenreTransformer().to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {n_params/1e6:.2f}M\n")

    # AdamW: Adam optimizer with decoupled weight decay regularization.
    # betas=(0.9, 0.95): standard momentum coefficients for language model training.
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY, betas=(0.9, 0.95))

    # LambdaLR wraps the optimizer and multiplies LR by lr_lambda(step) each step.
    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)

    # CrossEntropyLoss: measures how wrong the model's next-token probabilities are.
    # ignore_index=PAD: the PAD token is not a real prediction, so don't penalize it.
    criterion = nn.CrossEntropyLoss(ignore_index=PAD)

    # Mixed precision: only enabled on CUDA (CPU doesn't benefit from fp16).
    use_amp = (device.type == "cuda")
    scaler = torch.amp.GradScaler('cuda', enabled=use_amp)

    start_epoch = 1
    best_val_loss = float("inf")
    global_step = 0

    # --- Resume from checkpoint if one exists ---
    resume_path = os.path.join(CKPT_DIR, "latest.pt")
    if os.path.exists(resume_path):
        # Load everything needed to continue training exactly where it left off:
        # model weights, optimizer momentum buffers, scheduler state, epoch number.
        ckpt = torch.load(resume_path, map_location=device)
        model.load_state_dict(ckpt["model"])
        optimizer.load_state_dict(ckpt["optimizer"])
        scheduler.load_state_dict(ckpt["scheduler"])
        start_epoch = ckpt["epoch"] + 1
        best_val_loss = ckpt["best_val_loss"]
        global_step = ckpt.get("global_step", 0)
        print(f"Resumed from epoch {ckpt['epoch']} (best val: {best_val_loss:.4f})\n")
    else:
        print("Starting fresh training\n")

    # ---------------------------------------------------------------------------
    # Main training loop
    # ---------------------------------------------------------------------------
    for epoch in range(start_epoch, EPOCHS + 1):

        # ---- Training phase ----
        model.train()  # enables dropout (important: must call before each train phase)
        train_loss = 0.0
        optimizer.zero_grad(set_to_none=True)  # clear gradients at start of epoch

        pbar = tqdm(train_loader, desc=f"Epoch {epoch:3d}/{EPOCHS} [train]", leave=False)
        for step, (inp, target, genre) in enumerate(pbar):
            # Move data to GPU (non_blocking=True overlaps transfer with computation)
            inp = inp.to(device, non_blocking=True)
            target = target.to(device, non_blocking=True)
            genre = genre.to(device, non_blocking=True)

            # Forward pass in fp16 (faster on GPU)
            with torch.amp.autocast('cuda', enabled=use_amp):
                # model returns (B, T, vocab_size) logits
                logits = model(inp, genre)
                # Flatten to (B*T, vocab_size) vs (B*T,) for CrossEntropyLoss
                loss = criterion(logits.reshape(-1, logits.size(-1)), target.reshape(-1))
                # Divide by GRAD_ACCUM so accumulated gradients equal one full-batch gradient
                loss = loss / GRAD_ACCUM

            # Backward pass: compute gradients (scaled to avoid fp16 underflow)
            scaler.scale(loss).backward()

            # Only update weights every GRAD_ACCUM steps
            if (step + 1) % GRAD_ACCUM == 0:
                # Unscale before gradient clipping (clipping must happen on true-scale grads)
                scaler.unscale_(optimizer)
                # Gradient clipping: cap gradient norm at 1.0 to prevent exploding gradients
                nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                scaler.step(optimizer)   # apply the optimizer update
                scaler.update()          # adjust the fp16 scale factor for next step
                optimizer.zero_grad(set_to_none=True)
                scheduler.step()         # advance the LR schedule
                global_step += 1

            train_loss += loss.item() * GRAD_ACCUM  # undo the GRAD_ACCUM division for logging
            pbar.set_postfix(loss=f"{loss.item()*GRAD_ACCUM:.3f}")

        train_loss /= len(train_loader)

        # ---- Validation phase ----
        model.eval()   # disables dropout so evaluation is deterministic
        val_loss = 0.0
        with torch.no_grad():  # no gradient computation needed during validation
            for inp, target, genre in tqdm(val_loader, desc=f"Epoch {epoch:3d}/{EPOCHS} [val]  ", leave=False):
                inp = inp.to(device, non_blocking=True)
                target = target.to(device, non_blocking=True)
                genre = genre.to(device, non_blocking=True)
                with torch.amp.autocast('cuda', enabled=use_amp):
                    logits = model(inp, genre)
                    loss = criterion(logits.reshape(-1, logits.size(-1)), target.reshape(-1))
                val_loss += loss.item()

        val_loss /= max(1, len(val_loader))

        print(f"Epoch {epoch:3d}/{EPOCHS} | train {train_loss:.4f} | val {val_loss:.4f}")

        # ---- Save checkpoints ----

        # best_model.pt — saved whenever validation loss improves.
        # This is the checkpoint used for generation (best generalization).
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), os.path.join(CKPT_DIR, "best_model.pt"))

        # latest.pt — full training state saved every epoch for resuming.
        # Includes optimizer and scheduler state so training can resume exactly.
        torch.save({
            "epoch": epoch,
            "model": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(),
            "best_val_loss": best_val_loss,
            "global_step": global_step,
        }, os.path.join(CKPT_DIR, "latest.pt"))

        # epoch_XXX.pt — snapshot saved every 5 epochs as a historical archive.
        if epoch % 5 == 0:
            torch.save(model.state_dict(), os.path.join(CKPT_DIR, f"epoch_{epoch:03d}.pt"))

    print(f"\nBest val loss: {best_val_loss:.4f}")
    print(f"Checkpoint saved to {CKPT_DIR}/best_model.pt")


if __name__ == "__main__":
    main()
